// Modularized Enneagram Data for Assessments
const centersData = {
    "Head": {
        name: "The Head (Thinking) Center",
        types: "5, 6, 7",
        focus: "Security, Certainty, and Future Planning.",
        priorities: "They prioritize analyzing information, predicting outcomes, and understanding the world to avoid pain or danger. They lead with their intellect.",
        downplay: "They often downplay instincts and pure emotion, preferring to 'think through' their feelings before expressing them."
    },
    "Heart": {
        name: "The Heart (Feeling) Center",
        types: "2, 3, 4",
        focus: "Identity, Connection, and Validation.",
        priorities: "They prioritize relationships, how they are perceived by others, and emotional resonance. They lead with their ability to connect and influence.",
        downplay: "They often downplay their own true needs or objective facts if they conflict with the image or connection they are trying to maintain."
    },
    "Gut": {
        name: "The Gut (Instinctive) Center",
        types: "8, 9, 1",
        focus: "Autonomy, Justice, and Reality.",
        priorities: "They prioritize control, fairness, and gut-level knowing. They lead with their presence and a desire to impact the environment directly.",
        downplay: "They often downplay their own feelings (especially vulnerability) and over-thinking, preferring immediate action or stance."
    }
};

const enneagramTypesData = {
    1: {
        name: "The Reformer / Perfectionist",
        shortName: "Reformer",
        briefDescription: "The Rational, Idealistic Type: Principled, Purposeful, Self-Controlled, and Perfectionistic.",
        center: "Gut",
        relatingTo: {
            1: "Acknowledge their hard work and fairness. Avoid criticism.",
            2: "Be warm and appreciative. Don't take their help for granted.",
            3: "Be efficient and competent. Don't waste their time.",
            4: "Validate their feelings and uniqueness. Don't be dismissive.",
            5: "Respect their privacy and need for logic. Don't overwhelm them emotionally.",
            6: "Be consistent and trustworthy. Reduce their anxiety with clarity.",
            7: "Allow them freedom and fun, but gently ground them.",
            8: "Stand your ground respectfully. Be direct and honest.",
            9: "Encourage them to speak up. Don't pressure them too hard."
        },
        leadershipStyle: "Type Ones lead with high integrity, discipline, and a focus on improvement. They are principled and reliable, often creating orderly, efficient systems. However, they can become critical, rigid, or micromanage when things fall short of their high expectations.",
        leadershipDeepDive: "Type One leaders operate through a 'Comparison Filter.' They are constantly evaluating current reality against an internalized 'Ideal Standard.' This makes them exceptional at quality control, ethics, and long-term planning. They lead by example, often working harder than anyone else to ensure accuracy. Challenges arise when their 'Inner Critic' turns outward, causing them to focus more on what is wrong than what is right. In high-stakes environments, they excel in compliance, turnaround strategies, and establishing rigorous operational foundations.",
        coreMotivation: "To be right, to have integrity, to be balanced, accurate, and fair. They are driven by a need to improve themselves and the world.",
        basicDesire: "To be good, virtuous, and beyond reproach.",
        coreFear: "Of being corrupt, evil, defective, or fundamentally flawed. (Why you need to know this: Your fear drives your perfectionism. Recognizing it helps you realize that making a mistake doesn't make *you* bad.)",
        basicWeaknessVice: "Resentment (often experienced as righteous anger or irritation).",
        commonBlindSpots: [
            "You likely repress your anger until it explodes as resentment.",
            "You may not realize how critical your 'helpful corrections' sound to others.",
            "You assume everyone shares your high standards and get frustrated when they don't."
        ],
        blindSpotStrategies: [
            "Practice the 80/20 rule: Accept that 80% perfect is often enough to move forward.",
            "Reframe 'wrong' as 'different' to reduce immediate judgment of others' methods.",
            "Schedule time for pure fun with no goal to silence the inner critic."
        ],
        workImplications: "High school level: Imagine the person who always makes sure the homework is formatted perfectly and the rules are strictly followed. At work, they are the ones you trust to get the details 100% correct. They excel in quality control, ethics, and process improvement.",
        workStrengths: "Detail-oriented, ethical, reliable, organized, disciplined, high standards.",
        workStruggles: "Delegation (trusting others to do it right), flexibility, speed vs. perfection, dealing with ambiguity.",
        relationshipImplications: "They value loyalty and shared values. They can be critical of partners, but only because they want the best for them. They show love through being responsible and helpful.",
        growthPoint: 7, stressPoint: 4,
        growthPointExplanation: "Path to Growth: Integration toward Type 7. When healthy, Ones learn to be more spontaneous, joyful, and less rigid. They allow for mistakes and embrace variety.",
        growthStrategies: "1. Practice 'Intentional Imperfection' on low-stakes tasks to lower the inner critic. 2. Schedule 'Unstructured Time' weekly to practice spontaneity. 3. Use the '80/20 Rule' to determine when high standards are necessary versus when 'done is better than perfect.' 4. Practice vocalizing appreciation for others' effort, not just the result. 5. Engage in a hobby purely for fun with no measurable goal.",
        stressPointExplanation: "Stress Reaction: Disintegration toward Type 4. Under pressure, Ones become moody, withdrawn, and feel that no one else cares about quality as much as they do.",
        stressManagement: ["1. Recognize when the 'Internal Critic' is becoming destructive.", "2. Engage in physical grounding activities to move out of the mind.", "3. Journal about feelings without judging them as 'wrong' or 'unreasonable'."],
        wing1: 9, wing2: 2,
        wing1Explanation: "Wing 9 (The Peacemaker): Adds a sense of calm, detachment, and an ability to see multiple perspectives. Expanding here helps you relax and pick your battles.",
        wing2Explanation: "Wing 2 (The Helper): Adds warmth, empathy, and a focus on people rather than just rules. Expanding here helps you connect with your team on a human level."
    },
    2: {
        name: "The Helper / Giver",
        shortName: "Helper",
        briefDescription: "The Caring, Interpersonal Type: Demonstrative, Generous, People-Pleasing, and Possessive.",
        center: "Heart",
        relatingTo: {
            1: "Be responsible and ethical. Show them you care about doing things right.",
            2: "Connect emotionally. Express appreciation often.",
            3: "Support their goals. Affirm their success.",
            4: "Be compassionate and present. Don't fix their feelings.",
            5: "Respect their boundaries. Don't take their withdrawal personally.",
            6: "Be loyal and reassuring. Calm their fears.",
            7: "Join in their fun. Don't be a wet blanket.",
            8: "Be direct but loving. Stand up for yourself.",
            9: "Be patient and gentle. Encourage them."
        },
        leadershipStyle: "Type Twos lead through relationships and empathy. They are nurturing and supportive, excelling at motivating teams through appreciation. However, they may struggle with boundaries and direct feedback.",
        leadershipDeepDive: "Type Two leaders focus on the 'Interpersonal Operating System.' They believe that a happy, cared-for team is a productive team. They excel at identifying the individual motivations of their staff and providing the mentorship needed for growth. Their leadership is often hands-on and highly communicative. The risk for a Type Two leader is over-extending themselves to please others, which can lead to burnout or avoiding necessary but difficult performance conversations. They shine in HR, customer-facing roles, and collaborative team-building efforts.",
        coreMotivation: "To be loved, needed, and appreciated. They want to express their feelings for others and be indispensable.",
        basicDesire: "To feel wanted and loved for who they are.",
        coreFear: "Of being unwanted, unloved, unworthy of love, or dispensable. (Why you need to know this: This fear drives you to over-give. Realizing this helps you understand that you are valuable even when you aren't helping someone.)",
        basicWeaknessVice: "Pride (The belief that you alone can help everyone, while denying your own needs).",
        commonBlindSpots: [
            "You may not realize how intrusive your help can feel to independent people.",
            "You likely expect others to read your mind about your own needs, then get resentful when they don't.",
            "You might use flattery or assistance to 'buy' allegiance and love."
        ],
        blindSpotStrategies: [
            "Ask yourself 'What do I want?' before automatically saying yes to a request.",
            "Wait for someone to actually ask for help before offering it.",
            "Express your needs directly rather than hinting at them."
        ],
        workImplications: "The kid who always brings snacks and asks how your weekend was. In the workplace, they are the 'heart' of the team, excelling in HR, customer service, and mentoring.",
        workStrengths: "Building relationships, empathy, customer service, morale boosting, networking, anticipation of needs.",
        workStruggles: "Setting boundaries, delivering negative feedback, working alone for long periods, separating personal worth from work approval.",
        relationshipImplications: "Deeply committed and warm, but can become possessive or 'martyr-like' if they feel their efforts aren't acknowledged. They need frequent gratitude.",
        growthPoint: 4, stressPoint: 8,
        growthPointExplanation: "Path to Growth: Integration toward Type 4. Twos learn to connect with their own authentic needs and develop a unique identity separate from helping others.",
        growthStrategies: "1. Practice saying 'no' to one request per day to establish boundaries. 2. Spend 15 minutes daily in introspection to identify your own needs. 3. Ask for specific help from a colleague to practice receiving. 4. Journal about your feelings without relating them to anyone else. 5. Find a creative outlet that is purely for your own enjoyment.",
        stressPointExplanation: "Stress Reaction: Disintegration toward Type 8. Under extreme pressure, Twos can become surprisingly bossy, aggressive, and demanding.",
        stressManagement: ["1. Step back from 'fixing' others' problems when feeling overwhelmed.", "2. Practice direct communication instead of hinting at needs.", "3. Set clear time limits for your availability to others."],
        wing1: 1, wing2: 3,
        wing1Explanation: "Wing 1 (The Reformer): Adds a sense of conscience, duty, and objectivity. Expanding here helps you set clearer principles and boundaries.",
        wing2Explanation: "Wing 3 (The Achiever): Adds ambition, adaptability, and a focus on results. Expanding here helps you become more goal-oriented and efficient."
    },
    3: {
        name: "The Achiever / Performer",
        shortName: "Achiever",
        briefDescription: "The Success-Oriented, Pragmatic Type: Adaptable, Excelling, Driven, and Image-Conscious.",
        center: "Heart",
        relatingTo: {
            1: "Be competent and correct. Help them improve systems.",
            2: "Appreciate their help. Connect personally.",
            3: "Work hard. Acknowledge their success.",
            4: "Value their uniqueness. Don't be fake.",
            5: "Be logical and brief. Respect their time.",
            6: "Be loyal and prepared. Reassure them.",
            7: "Be positive and open. Keep up with their pace.",
            8: "Be direct and confident. Don't waste time.",
            9: "Be patient. Don't push them too hard."
        },
        leadershipStyle: "Type Threes are dynamic, goal-oriented, and charismatic. They lead with high energy and focus on results. They can be workaholics and may prioritize image over authentic connection.",
        leadershipDeepDive: "Type Three leaders are the 'Engine of Productivity.' They are masters of the 'Outcome Filter,' always looking for the most efficient path to success. They are often the face of the organization, possessing a natural ability to inspire confidence and market the team's wins. However, they may struggle with the 'becoming' process, focusing so much on the goal that they neglect the emotional health of the team. They excel in high-pressure sales environments, start-up growth phases, and roles requiring rapid execution.",
        coreMotivation: "To be valuable, successful, and admired. They need to be affirmed to feel worthwhile.",
        basicDesire: "To feel worthwhile and competent.",
        coreFear: "Of being worthless, a failure, or without inherent value apart from their achievements. (Why you need to know this: This fear drives your workaholism. Seeing it helps you realize you are more than your resume.)",
        basicWeaknessVice: "Deceit (Deceiving yourself that you are only your image/role).",
        commonBlindSpots: [
            "You often confuse your true self with your job or role.",
            "You might cut corners or gloss over details to get to the 'win' faster.",
            "You can be impatient with feelings or 'slow' people who block progress."
        ],
        blindSpotStrategies: [
            "Define success metrics that include team health, not just output.",
            "Practice listening without trying to 'solve' or 'fix' immediately.",
            "Share a failure or struggle to build authentic connection."
        ],
        workImplications: "The student who wants to be class president and get the highest grades. At work, they are the competitive high-performers who hit every target and drive growth.",
        workStrengths: "Efficiency, productivity, marketing, goal-setting, motivating others, adaptability.",
        workStruggles: "Burnout, impatience with process/feelings, authenticity, prioritizing image over substance, admitting failure.",
        relationshipImplications: "Can focus more on how the relationship 'looks' to others. They need to practice being real and vulnerable.",
        growthPoint: 6, stressPoint: 9,
        growthPointExplanation: "Path to Growth: Integration toward Type 6. Threes become more cooperative, loyal to the group, and honest about their feelings rather than just their image.",
        growthStrategies: "1. Share a personal failure or struggle with a trusted peer to build authenticity. 2. Practice 'Process Praise'—compliment the effort and teamwork, not just the win. 3. Commit to a project where you are not the leader. 4. Schedule one day a week with no work-related goals. 5. Practice active listening without planning your next achievement-based response.",
        stressPointExplanation: "Stress Reaction: Disintegration toward Type 9. Under stress, Threes become disengaged, apathetic, and lose their characteristic drive.",
        stressManagement: ["1. Recognize the early signs of 'autopilot' behavior.", "2. Reconnect with core values that are not tied to work.", "3. Engage in physical exercise to reconnect with the body's needs."],
        wing1: 2, wing2: 4,
        wing1Explanation: "Wing 2 (The Helper): Adds charm, people skills, and generosity. Expanding here helps you connect with your team and mentor others.",
        wing2Explanation: "Wing 4 (The Individualist): Adds depth, creativity, and introspection. Expanding here helps you bring authenticity and meaning to your work."
    },
    4: {
        name: "The Individualist / Romantic",
        shortName: "Individualist",
        briefDescription: "The Sensitive, Withdrawn Type: Expressive, Dramatic, Self-Absorbed, and Temperamental.",
        center: "Heart",
        relatingTo: {
            1: "Respect their standards. Be authentic.",
            2: "Connect emotionally. Show appreciation.",
            3: "Value their achievements. Be real.",
            4: "Understand their depth. Don't dismiss feelings.",
            5: "Respect their space. Engage intellectually.",
            6: "Be loyal and consistent. Reassure them.",
            7: "Be positive but don't force cheer. Be deep.",
            8: "Be honest and direct. Don't be fake.",
            9: "Be gentle and accepting. Don't pressure."
        },
        leadershipStyle: "Type Four leaders bring a unique blend of authenticity, creativity, and emotional depth to their roles. They inspire others by being true to themselves and encouraging self-expression and meaningful work within their teams. They value originality and can often see possibilities that others miss. However, their introspective nature and emotional sensitivity can sometimes lead to moodiness, withdrawal, or difficulty with purely practical or mundane demands. They may take feedback very personally or struggle if they feel misunderstood or unappreciated for their unique contributions.",
        leadershipDeepDive: "Type Four leaders bring the 'Depth and Authenticity Filter' to the workplace. They are often the creative visionaries who aren't afraid to challenge the status quo to find more meaningful ways of working. They excel at identifying the 'subtext' in a room and are highly empathetic to the emotional states of their team. The challenge for a Four leader is the 'Comparison Trap,' where they may feel their team is never quite as ideal as they imagined. They shine in design, branding, strategy, and roles requiring high emotional intelligence.",
        coreMotivation: "To find themselves and their significance. They want to create an identity out of their inner experience.",
        basicDesire: "To create a unique identity and find personal significance.",
        coreFear: "Of having no identity, no personal significance, or being plain/ordinary.",
        basicWeaknessVice: "Envy (Feeling that others possess a quality of happiness/wholeness that you lack).",
        commonBlindSpots: [
            "You may be self-absorbed and unaware of how your moodiness affects the room.",
            "You might withdraw to punish others or make them come to you.",
            "You often focus on what is missing rather than what is present and good."
        ],
        blindSpotStrategies: [
            "Focus on objective facts and data when feeling moody.",
            "Create a daily gratitude list to combat the focus on what's missing.",
            "Engage in physical activity to get out of your head and into your body."
        ],
        workImplications: "The artistic student with a unique style. At work, they excel in design, strategy, and roles requiring emotional depth or 'out-of-the-box' thinking.",
        workStrengths: "Creativity, empathy, vision, depth, aesthetic sensibility, questioning the status quo.",
        workStruggles: "Routine/mundane tasks, taking things personally, mood fluctuations affecting productivity, feeling misunderstood.",
        relationshipImplications: "Intense and empathetic. They aren't afraid of the difficult parts of life, but can be self-absorbed and sensitive to perceived slights.",
        growthPoint: 1, stressPoint: 2,
        growthPointExplanation: "Path to Growth: Integration toward Type 1. Fours become more disciplined, objective, and grounded in practical action rather than just feelings.",
        growthStrategies: "1. Establish a rigid morning routine to ground your emotional energy. 2. Complete one mundane, practical task before moving to creative work. 3. Practice 'Emotional Labeling'—recognize a feeling without letting it dictate your schedule. 4. Focus on serving the team's objective needs rather than your own creative ideals. 5. Set measurable deadlines for your creative projects.",
        stressPointExplanation: "Stress Reaction: Disintegration toward Type 2. Under stress, Fours become overly dependent on others for emotional validation and connection.",
        stressManagement: ["1. Limit social media comparison when feeling low.", "2. Practice self-soothing techniques that don't involve other people.", "3. Write down three objective facts about your current situation to combat moodiness."],
        wing1: 3, wing2: 5,
        wing1Explanation: "Wing 3 (The Achiever): Adds ambition, drive, and a focus on presentation. Expanding here helps you bring your creative visions to market.",
        wing2Explanation: "Wing 5 (The Investigator): Adds objectivity, intellectual depth, and observation. Expanding here helps you analyze your feelings rather than drowning in them."
    },
    5: {
        name: "The Investigator / Observer",
        shortName: "Investigator",
        briefDescription: "The Intense, Cerebral Type: Perceptive, Innovative, Secretive, and Isolated.",
        center: "Head",
        relatingTo: {
            1: "Be logical and precise. Respect their standards.",
            2: "Appreciate their warmth but set boundaries.",
            3: "Be competent and efficient. Don't be flashy.",
            4: "Engage intellectually. Respect their depth.",
            5: "Respect privacy. Connect through ideas.",
            6: "Be reliable and logical. Reduce uncertainty.",
            7: "Be interesting. Don't overwhelm with emotion.",
            8: "Be direct and strong. Don't be intrusive.",
            9: "Be gentle and patient. Give them space."
        },
        leadershipStyle: "Type Five leaders are typically analytical, strategic, and visionary, valuing knowledge, competence, and foresight. They lead by providing well-thought-out insights, encouraging independent thinking, and maintaining a calm, objective demeanor. They prefer to understand systems deeply before acting. However, their tendency to withdraw and conserve energy can make them seem detached, overly reserved with information or resources, or dismissive of emotional considerations in decision-making. They might struggle with the interpersonal aspects of leadership or appear unapproachable if they retreat too much into their own thoughts.",
        leadershipDeepDive: "Type Five leaders operate through the 'Expertise and Information Filter.' They believe that knowledge is power and safety. They are often the calmest people in a crisis, using logic to navigate complexity. They are highly strategic and objective. However, they may struggle with the social demands of leadership, viewing team interactions as 'energy drains.' They excel in technical leadership, financial strategy, and R&D. To be more effective, they must learn to share information as a bridge to connection rather than hoarding it as a resource.",
        coreMotivation: "To be competent and knowledgeable. They want to understand the world and possess skills to navigate it.",
        basicDesire: "To be capable and independent.",
        coreFear: "Of being helpless, useless, incapable, or overwhelmed.",
        basicWeaknessVice: "Avarice (Hoarding of time, energy, and resources).",
        commonBlindSpots: [
            "You likely appear more intellectually arrogant or distant than you intend.",
            "You may withhold information simply because no one asked the exact right question.",
            "You underestimate how much your team needs emotional connection, not just data."
        ],
        blindSpotStrategies: [
            "Share your thoughts before they feel 100% perfect or complete.",
            "Set a timer for social engagement so you know there is an end point.",
            "Practice physical engagement (eye contact, nodding) to show you are listening."
        ],
        workImplications: "The quiet student who knows everything about a niche topic. At work, they are the tech experts, engineers, and strategists who solve complex problems.",
        workStrengths: "Objective analysis, expertise, complex problem solving, calm in crisis, strategic planning.",
        workStruggles: "Social exhaustion, communication, sharing information, moving from planning to action, empathy.",
        relationshipImplications: "Value space and intellectual connection. They show love through sharing information and objective support, but need plenty of 'alone time.'",
        growthPoint: 8, stressPoint: 7,
        growthPointExplanation: "Path to Growth: Integration toward Type 8. Fives move out of their minds and into the world, becoming more assertive, confident, and action-oriented.",
        growthStrategies: "1. Practice vocalizing your ideas before you feel they are 'fully baked.' 2. Lead a meeting with a focus on physical presence and energy. 3. Share a piece of information you would normally keep to yourself. 4. Engage in physical activity (like weightlifting) to connect with your gut instinct. 5. Practice 'direct eye contact' in your one-on-one meetings.",
        stressPointExplanation: "Stress Reaction: Disintegration toward Type 7. Under stress, Fives become scattered, frantic, and seek superficial distractions.",
        stressManagement: ["1. Create a quiet, stimulus-free environment when feeling overwhelmed.", "2. Limit the number of open 'tabs' (tasks) you are managing.", "3. Re-read familiar, comforting research to ground your focus."],
        wing1: 4, wing2: 6,
        wing1Explanation: "Wing 4 (The Individualist): Adds creativity, intuition, and a personal touch. Expanding here helps you connect your intellect with your own unique perspective.",
        wing2Explanation: "Wing 6 (The Loyalist): Adds loyalty, troubleshooting, and a focus on community. Expanding here helps you collaborate and trust your team."
    },
    6: {
        name: "The Loyalist / Skeptic",
        shortName: "Loyalist",
        briefDescription: "The Committed, Security-Oriented Type: Engaging, Responsible, Anxious, and Suspicious.",
        center: "Head",
        relatingTo: {
            1: "Be responsible and consistent. Follow rules.",
            2: "Be supportive and warm. Reassure them.",
            3: "Be productive and reliable. Help them succeed.",
            4: "Be authentic and emotional. Validate them.",
            5: "Be logical and calm. Respect their mind.",
            6: "Build trust. Be loyal and consistent.",
            7: "Be positive and fun. Don't be reckless.",
            8: "Be strong and direct. Show loyalty.",
            9: "Be patient and gentle. Don't force them."
        },
        leadershipStyle: "Type Six leaders are typically responsible, hardworking, and deeply committed to their teams and organizations. They are excellent troubleshooters, anticipating potential problems and preparing for contingencies. They value security, loyalty, and clear guidelines, and work to create a sense of trust and predictability. However, their underlying anxiety can lead to indecisiveness, excessive questioning of authority (or, conversely, over-reliance on it), or resistance to change if it feels threatening. They may struggle with ambiguity and can sometimes project their own fears onto situations or people.",
        leadershipDeepDive: "Type Six leaders utilize the 'Risk and Contingency Filter.' They are the ultimate protectors of the organization, always three steps ahead of potential problems. They are fiercely loyal to their staff and create deep bonds of trust. Their leadership is often cautious and thorough. The challenge for a Six leader is 'analysis paralysis' or projecting their own anxieties onto others. They shine in operations, crisis management, and roles where reliability is the most important metric. They are the backbone of any healthy culture.",
        coreMotivation: "To find security and support. They seek to feel safe and prepared, often by anticipating what could go wrong.",
        basicDesire: "To have security and guidance.",
        coreFear: "Of being without support or guidance.",
        basicWeaknessVice: "Fear/Anxiety (Constantly scanning the horizon for threats).",
        commonBlindSpots: [
            "You may project your own fears onto others (accusing them of being untrustworthy).",
            "Your 'devil's advocacy' can sound like pessimism or lack of faith to your team.",
            "You often look for authority figures to either obey or rebel against."
        ],
        blindSpotStrategies: [
            "Fact-check your fears: Ask 'Is this true, or is this a feeling?'",
            "Trust your gut instinct on small decisions to build confidence.",
            "Limit your information intake (news/data) when feeling anxious."
        ],
        workImplications: "The student who always asks 'Is this on the test?' They are incredibly reliable, hard-working, and the backbone of any stable team.",
        workStrengths: "Risk management, loyalty, troubleshooting, preparation, team building, reliability.",
        workStruggles: "Decision paralysis, excessive worry, skepticism of new ideas, lack of self-confidence.",
        relationshipImplications: "Loyal forever once trust is earned. They can be prone to worrying about the future of the relationship and need consistent reassurance.",
        growthPoint: 9, stressPoint: 3,
        growthPointExplanation: "Path to Growth: Integration toward Type 9. Sixes become more relaxed, trusting, and connected to their own inner stability and gut feelings.",
        growthStrategies: "1. When anxious, ask yourself: 'Is this a real threat or a mental story?' 2. Practice delegating a task and intentionally not checking on it. 3. Use deep breathing exercises to calm the nervous system before big decisions. 4. Write down three things that went right at the end of each day. 5. Practice trusting your first instinct on small decisions.",
        stressPointExplanation: "Stress Reaction: Disintegration toward Type 3. Under stress, Sixes become competitive and obsessed with image and productivity to mask their fear.",
        stressManagement: ["1. Reach out to a trusted mentor for a 'reality check.'", "2. Physical grounding (walking, stretching) to get out of the 'worry loop.'", "3. Limit your consumption of news or negative data."],
        wing1: 5, wing2: 7,
        wing1Explanation: "Wing 5 (The Investigator): Adds analysis, objectivity, and focus. Expanding here helps you back up your fears with facts and logic.",
        wing2Explanation: "Wing 7 (The Enthusiast): Adds optimism, energy, and future-thinking. Expanding here helps you see possibilities rather than just threats."
    },
    7: {
        name: "The Enthusiast / Epicure",
        shortName: "Enthusiast",
        briefDescription: "The Spontaneous, Versatile Type: Acquisitive, Scattered, and Future-Oriented.",
        center: "Head",
        relatingTo: {
            1: "Be responsible and fun. Don't be too rigid.",
            2: "Be appreciative and engaged. Don't smother.",
            3: "Be successful and exciting. Keep up.",
            4: "Be authentic and deep. Don't be superficial.",
            5: "Be interesting. Respect their space.",
            6: "Be loyal and fun. Don't add to anxiety.",
            7: "Share adventures. Enjoy life together.",
            8: "Be strong and direct. Have fun.",
            9: "Be easygoing. Don't force them."
        },
        leadershipStyle: "Type Sevens lead with optimism and innovation. They are energetic and motivate others with excitement. They can be scattered and may avoid difficult conversations or follow-through.",
        leadershipDeepDive: "Type Seven leaders operate through the 'Possibility and Variety Filter.' They are the visionary light-starters of the Enneagram, capable of generating ideas that disrupt entire industries. They lead with high energy, positivity, and a 'sky is the limit' attitude. This makes them magnetic motivators. However, they may struggle with the 'grind' of follow-through or hearing negative news. They shine in start-ups, marketing, creative direction, and any role requiring high-level innovation. To grow, they must learn that satisfaction often comes from finishing one thing rather than starting ten.",
        coreMotivation: "To be satisfied and content. They seek pleasure and avoid pain, wanting to experience as much of life as possible.",
        basicDesire: "To be happy and have their needs fulfilled.",
        coreFear: "Of being deprived and in pain.",
        basicWeaknessVice: "Gluttony (An insatiable desire for *more*—more ideas, more experiences, more stimulation).",
        commonBlindSpots: [
            "You often reframe negative realities into positives to avoid dealing with them.",
            "You may leave a trail of unfinished projects that frustrates your team.",
            "You likely overestimate your capacity and overcommit."
        ],
        blindSpotStrategies: [
            "Practice 'sticking with it' for just 1 hour longer than comfortable.",
            "Journal about negative feelings instead of distracting yourself.",
            "Focus on quality over quantity in your experiences."
        ],
        workImplications: "The kid who is in five different clubs and always has a new idea. At work, they are the sales stars, creative directors, and start-up entrepreneurs.",
        workStrengths: "Innovation, brainstorming, optimism, adaptability, quick thinking, high energy.",
        workStruggles: "Follow-through, routine tasks, dealing with negative feedback/conflict, impulsivity.",
        relationshipImplications: "Fun and adventurous. They keep things light and exciting, but may struggle when the relationship requires heavy emotional labor or boredom.",
        growthPoint: 5, stressPoint: 1,
        growthPointExplanation: "Path to Growth: Integration toward Type 5. Sevens learn to focus deeply, master their craft, and find satisfaction in depth rather than just novelty.",
        growthStrategies: "1. Commit to finishing one project before starting a new one. 2. Practice 'Silence' for 10 minutes a day with no stimulation. 3. Lean into a difficult conversation instead of using humor to deflect. 4. Focus on the details of one specific process until you master it. 5. Practice 'Single-Tasking'—no multitasking for two hours each day.",
        stressPointExplanation: "Stress Reaction: Disintegration toward Type 1. Under stress, Sevens become critical, rigid, and surprisingly grumpy and demanding.",
        stressManagement: ["1. Acknowledge that discomfort is a temporary part of growth.", "2. Use a structured to-do list to organize your scattered energy.", "3. Practice gratitude for the present moment."],
        wing1: 6, wing2: 8,
        wing1Explanation: "Wing 6 (The Loyalist): Adds loyalty, responsibility, and awareness of risk. Expanding here helps you ground your ideas in reality.",
        wing2Explanation: "Wing 8 (The Challenger): Adds confidence, decisiveness, and power. Expanding here helps you push your ideas through to completion."
    },
    8: {
        name: "The Challenger / Protector",
        shortName: "Challenger",
        briefDescription: "The Powerful, Dominating Type: Self-Confident, Decisive, Willful, and Confrontational.",
        center: "Gut",
        relatingTo: {
            1: "Be honest and fair. Stand your ground.",
            2: "Be appreciative. Don't take advantage.",
            3: "Be competent. Don't be fake.",
            4: "Be real. Don't be emotional manipulative.",
            5: "Be direct. Respect their mind.",
            6: "Be loyal. Don't betray them.",
            7: "Be fun and strong. Keep up.",
            8: "Be strong and honest. Respect boundaries.",
            9: "Be gentle. Don't steamroll them."
        },
        leadershipStyle: "Type Eights lead with power and decisiveness. They are protective of their team and drive results through willpower. They can be domineering and intimidating if unaware.",
        leadershipDeepDive: "Type Eight leaders use the 'Strength and Impact Filter.' They are the natural 'Captains' of the system, capable of moving mountains through sheer willpower. They lead by making quick, bold decisions and standing up for their people. They value honesty and directness above all else. The risk for an Eight leader is that their 'Vibe' is so strong it can unintentionally silence or intimidate others. They excel in C-suite leadership, high-stakes negotiations, and roles requiring intense courage. They are the ultimate champions for the underdog.",
        coreMotivation: "To protect themselves and maintain control. They want to assert their strength and resist being vulnerable.",
        basicDesire: "To be strong and autonomous.",
        coreFear: "Of being harmed, controlled, or violated.",
        basicWeaknessVice: "Lust (Intensity/Excess). A need to push against reality to feel alive and in control.",
        commonBlindSpots: [
            "You often don't realize how intimidating your 'normal' energy is to others.",
            "You deny your own vulnerability and needs, leading to exhaustion.",
            "You may view compromise as weakness."
        ],
        blindSpotStrategies: [
            "Pause for 3 seconds before responding to lower the intensity.",
            "Ask 'What is your perspective?' and truly listen.",
            "Admit a small weakness or error to build trust."
        ],
        workImplications: "The student who stands up to bullies. At work, they are the CEOs and managers who aren't afraid of a fight to get the right thing done.",
        workStrengths: "Decisiveness, courage, big-picture strategy, protecting the team, moving obstacles.",
        workStruggles: "Collaboration, patience, sensitivity to feelings, intimidation, micromanagement (via control).",
        relationshipImplications: "Passionate and fiercely protective. They value honesty above all else. They can be difficult to get close to because they fear being weak.",
        growthPoint: 2, stressPoint: 5,
        growthPointExplanation: "Path to Growth: Integration toward Type 2. Eights connect with their hearts, becoming more empathetic, nurturing, and compassionate in their leadership.",
        growthStrategies: "1. Practice 'Active Listening'—repeat what someone said before you respond. 2. Ask for your team's input before stating your own opinion. 3. Share a vulnerability or a mistake you made to build team safety. 4. Practice 'Softness' in your physical tone and volume. 5. Perform an anonymous act of kindness for a team member.",
        stressPointExplanation: "Stress Reaction: Disintegration toward Type 5. Under threat, Eights become surprisingly secretive, withdrawn, and suspicious of others.",
        stressManagement: ["1. Notice when you are pulling away into 'fortress mode.'", "2. Trust at least one person with your concerns.", "3. Physical movement (gym, boxing) to release built-up intensity."],
        wing1: 7, wing2: 9,
        wing1Explanation: "Wing 7 (The Enthusiast): Adds energy, quick thinking, and a future focus. Expanding here helps you be more visionary and social.",
        wing2Explanation: "Wing 9 (The Peacemaker): Adds calm, patience, and receptivity. Expanding here helps you pick your battles and listen to others."
    },
    9: {
        name: "The Peacemaker / Mediator",
        shortName: "Peacemaker",
        briefDescription: "The Easygoing, Self-Effacing Type: Receptive, Reassuring, Agreeable, and Complacent.",
        center: "Gut",
        relatingTo: {
            1: "Be calm and fair. Don't be critical.",
            2: "Be kind and appreciative. Connect.",
            3: "Be supportive. Don't push too hard.",
            4: "Be gentle. Listen to their feelings.",
            5: "Respect their space. Be calm.",
            6: "Be reassuring and loyal. Reduce stress.",
            7: "Be positive. Join in the fun.",
            8: "Be direct but kind. Don't be aggressive.",
            9: "Be patient. Encourage their voice."
        },
        leadershipStyle: "Type Nine leaders are typically inclusive, steady, and supportive, striving to create harmonious and stable work environments. They are excellent mediators, skilled at seeing multiple perspectives and fostering consensus. They lead with a calm, reassuring presence and value the well-being of their team. However, their desire to avoid conflict can lead them to be overly passive, indecisive on tough issues, or struggle with setting clear priorities if it means displeasing someone. They might become complacent or disengaged if the environment is too stressful or demanding.",
        leadershipDeepDive: "Type Nine leaders operation through the 'Harmony and Inclusion Filter.' They are the master mediators and consensus builders. They ensure that every voice on the team is heard. They lead with a calm, steady presence that reduces team stress and fosters a psychologically safe environment. They are excellent at seeing multiple perspectives and synthesizing them into a unified plan. The challenge for a Nine leader is 'Self-Forgetting,' where they may avoid taking a necessary stand to keep the peace. They shine in mediation, project management, and roles where steady, consistent progress is key.",
        coreMotivation: "To maintain inner and outer peace. They want to avoid tension and discord, creating harmony in their environment.",
        basicDesire: "To have inner stability and 'peace of mind.'",
        coreFear: "Of loss, separation, and fragmentation.",
        basicWeaknessVice: "Sloth (Psychological/Spiritual inertia—staying in comfort zones to avoid waking up to life's demands).",
        commonBlindSpots: [
            "You may be passive-aggressive (stubbornness) instead of saying 'no' directly.",
            "You often merge with others' agendas and lose your own priorities.",
            "You minimize problems until they become crises."
        ],
        blindSpotStrategies: [
            "State your opinion first in a meeting, before hearing others.",
            "Set a firm deadline for decisions to avoid procrastination.",
            "Practice saying 'I disagree' in low-stakes situations."
        ],
        workImplications: "The student who gets along with everyone. At work, they are the mediators and project managers who keep everything running smoothly without drama.",
        workStrengths: "Mediation, consensus building, patience, inclusivity, consistency, reducing team stress.",
        workStruggles: "Decisiveness, conflict resolution, asserting own agenda, procrastination, prioritizing.",
        relationshipImplications: "Very easygoing and accepting. However, they might 'agree' just to avoid a fight while feeling differently inside. They need encouragement to speak up.",
        growthPoint: 3, stressPoint: 6,
        growthPointExplanation: "Path to Growth: Integration toward Type 3. Nines become more assertive, set goals, and acknowledge their own value and personal power.",
        growthStrategies: "1. State your opinion first in the next three meetings. 2. Set three 'Non-Negotiable' goals for yourself each day. 3. Practice saying 'I disagree' in a calm, constructive way. 4. Engage in high-energy activity to boost your personal 'presence.' 5. Acknowledge and name your own successes to your manager.",
        stressPointExplanation: "Stress Reaction: Disintegration toward Type 6. Under stress, Nines become anxious, worried, and overly cautious about the future.",
        stressManagement: ["1. Break big, scary tasks into tiny, five-minute steps.", "2. Focus on what you *can* control right now.", "3. Practice grounding exercises (5-4-3-2-1 technique)."],
        wing1: 8, wing2: 1,
        wing1Explanation: "Wing 8 (The Challenger): Adds strength, assertiveness, and energy. Expanding here helps you take charge and set boundaries.",
        wing2Explanation: "Wing 1 (The Reformer): Adds structure, discipline, and idealism. Expanding here helps you organize your life and stick to priorities."
    }
};

const questions = [
    { text: "When facing a difficult task, my primary concern is often:", options: ["Ensuring it's done correctly and to the highest standard.", "How it will affect my relationships and if I can help others.", "Achieving the goal efficiently and being recognized for success.", "Whether it feels meaningful and authentic to me personally."], scoring: [[1], [2], [3], [4]] },
    { text: "I feel most anxious or unsettled when I perceive a threat of:", options: ["Being seen as flawed, wrong, or unethical.", "Being unwanted, unloved, or dispensable to others.", "Failing or being seen as incompetent or worthless.", "Lacking a unique identity or profound significance."], scoring: [[1], [2], [3], [4]] },
    { text: "My natural tendency in a group is to:", options: ["Observe and understand before actively participating.", "Look for potential problems and ensure we are prepared.", "Bring energy, enthusiasm, and explore new possibilities.", "Take charge or ensure things are moving forward decisively."], scoring: [[5], [6], [7], [8]] },
    { text: "I am most driven by a need for:", options: ["Competence and understanding; I want to know how things work.", "Security and support; I need to feel safe and guided.", "Satisfaction and new experiences; I want to avoid boredom.", "Control over my environment and to protect myself."], scoring: [[5], [6], [7], [8]] },
    { text: "When conflict arises, my first instinct is often to:", options: ["Try to smooth things over and maintain harmony.", "Analyze it objectively and understand all sides.", "Confront it directly to resolve it and assert my position.", "Feel anxious and seek reassurance or prepare for the worst."], scoring: [[9], [5], [8], [6]] },
    { text: "A common piece of feedback I receive is that I can be:", options: ["Too critical or demanding (of self and others).", "Overly accommodating or focused on others' needs.", "Too competitive or image-conscious.", "Too moody, dramatic, or self-absorbed."], scoring: [[1], [2], [3], [4]] },
    { text: "I tend to avoid situations or feelings that make me feel:", options: ["Overwhelmed by demands or strong emotions.", "Unsupported, uncertain, or at risk.", "Trapped, bored, or in physical/emotional pain.", "Vulnerable or controlled by others."], scoring: [[5], [6], [7], [8]] },
    { text: "My greatest struggle is often with:", options: ["My inner critic and feeling things aren't good enough.", "Needing to be needed and feeling prideful.", "Focusing too much on achieving, losing authenticity.", "Feeling like something is missing in me compared to others."], scoring: [[1], [2], [3], [4]] },
    { text: "I am most comfortable when:", options: ["I have my own space and time to think and recharge.", "I know what to expect and feel supported by those I trust.", "I am exploring exciting new options and possibilities.", "I am in control and feel strong and capable."], scoring: [[5], [6], [7], [8]] },
    { text: "In relationships, I primarily seek:", options: ["Peace and stability, avoiding conflict as much as possible.", "To be a source of help and support, wanting love in return.", "To be admired for my accomplishments and talents.", "Deep, authentic connection, even if intense or complicated."], scoring: [[9], [2], [3], [4]] },
    { text: "Others might not realize that I often feel:", options: ["A deep sense of responsibility for things to be just right.", "A fear of not being truly wanted for myself.", "Insecure about my intrinsic worth, driving my need for validation.", "More ordinary than I let on, despite my desire to be unique."], scoring: [[1], [2], [3], [4]] },
    { text: "A hidden aspect of my personality might be:", options: ["My rich inner world and complex thoughts.", "How much I test people to see if they are truly trustworthy.", "A fear of missing out that drives my constant activity.", "A softer, more vulnerable side that I protect fiercely."], scoring: [[5], [6], [7], [8]] },
    { text: "I sometimes 'go along to get along' to such an extent that I:", options: ["Lose track of my own priorities and desires.", "Feel resentful later but struggle to express it.", "Get involved in things I'm not truly interested in.", "Avoid making decisions that might cause disagreement."], scoring: [[9], [9], [9], [9]] },
    { text: "When I'm truly stressed, I'm most likely to:", options: ["Become overly critical and rigid (my way or the highway).", "Try harder to please others, becoming clingy.", "Push myself even harder, becoming more image-focused.", "Withdraw into my feelings and feel misunderstood."], scoring: [[1], [2], [3], [4]] },
    { text: "When under pressure, my default reaction is:", options: ["Detach and analyze to conserve my resources.", "Become more anxious and scan for worst-case scenarios.", "Seek distractions or new options to escape pressure.", "Become more assertive and push back against the pressure."], scoring: [[5], [6], [7], [8]] },
    { text: "I feel most content when:", options: ["Things are orderly and I've done my best.", "I feel deeply connected and appreciated.", "I am successfully achieving my goals.", "I am able to express my unique self."], scoring: [[1], [2], [3], [4]] },
    { text: "My ideal environment is one where:", options: ["I have space to pursue my interests without interruption.", "I feel secure and can trust those around me.", "There's positive energy and opportunities for enjoyment.", "I have autonomy and the power to make an impact."], scoring: [[5], [6], [7], [8]] },
    { text: "A recurring theme in my life is the tension between:", options: ["My desire for perfection and an imperfect world.", "My need to be loved and fear of being a burden.", "My drive for success and fear of being seen as a failure.", "My longing for connection and feeling different."], scoring: [[1], [2], [3], [4]] },
    { text: "I often wrestle with:", options: ["Desire for knowledge vs. fear of being overwhelmed.", "Need for certainty vs. tendency to doubt authority.", "Urge for pleasure vs. difficulty facing pain.", "Drive to be strong vs. fear of being weak."], scoring: [[5], [6], [7], [8]] },
    { text: "When making life decisions, I tend to:", options: ["Find a compromise that keeps everyone happy.", "Rely on my principles and what is 'right'.", "Consider how it will impact my image and success.", "Trust my intuition and what feels most authentic."], scoring: [[9], [1], [3], [4]] },
    { text: "People might say I sometimes overlook:", options: ["The emotional impact of my directness.", "My own needs while keeping the peace.", "The value of just 'being' vs. always 'doing'.", "How my need for order can feel restrictive to others."], scoring: [[8], [9], [3], [1]] },
    { text: "I'm often drawn to activities that involve:", options: ["Helping or nurturing others.", "Deep investigation and learning complex subjects.", "Planning for the future and ensuring safety.", "Experiencing novelty, fun, and variety."], scoring: [[2], [5], [6], [7]] },
    { text: "One of my biggest unspoken fears is:", options: ["That I am inherently flawed or bad.", "That I am ultimately unlovable.", "That I am worthless without achievements.", "That I have no true identity."], scoring: [[1], [2], [3], [4]] },
    { text: "Deep down, I'm afraid of:", options: ["Being helpless or incapable.", "Being without support or guidance.", "Being trapped in pain or boredom.", "Being harmed or controlled by others."], scoring: [[5], [6], [7], [8]] },
    { text: "My 'Achilles' heel' is my tendency towards:", options: ["Resentment when things aren't as they 'should' be.", "Pride in my helpfulness.", "Self-deceit regarding my true image.", "Envy of what others possess."], scoring: [[1], [2], [3], [4]] },
    { text: "A pattern I have to work against is:", options: ["Hoarding my time/energy (Avarice).", "Excessive worry (Fear/Anxiety).", "Over-indulging to avoid discomfort (Gluttony).", "Needing to assert control (Lust)."], scoring: [[5], [6], [7], [8]] },
    { text: "To avoid discomfort, I might sometimes:", options: ["Merge with others and neglect my own desires.", "Become overly agreeable despite reservations.", "Downplay my accomplishments to fit in.", "Procrastinate on tasks that feel overwhelming."], scoring: [[9], [9], [9], [9]] }
];
